model_name: vit_base_patch16_224.dino
data_root: data/VOCdevkit/VOC2012
train_datapath: ImageSets/Segmentation/train.txt
val_datapath: ImageSets/Segmentation/val.txt
resize_dim: 512
lr: 0.005
batch_size: 16
num_epochs: 3
remove_background: true
